/*
 * λ m4d_i2c.h
 *
 * Created: 17.12.2020 1:03:28
 *  Author: m4d
 */ 
#ifndef M4D_I2C_H_
#define M4D_I2C_H_

#include "main.h"

void m4d_i2c_init_as_slave(void);
uint8_t execute_command_timer();
void update_i2c_data_timer();
void i2c_send_debug_int_var_oled(char *varName, uint16_t varValue);
void I2C_Slave_Init(uint8_t slave_address);

#define ME_ADDR 0x4D // последний резрешение отклика на адрес

#define REC_MODE 0
#define PLAY_MODE 1
#define STOP_MODE 2
#define REWIND_MODE 3
#define FORWARD_MODE 4
#define PAUSE_MODE 5
#define REWIND_SEARCH_MODE 6
#define FORWARD_SEARCH_MODE 7
#define REC_MODE_GEN 8
#define REC_MODE_PLAY 9
#define REWIND_LITTLE_MODE 10
#define FORWARD_LITTLE_MODE 11

#define I2C_SERVO_START_TRANSACTION_SYMBOL_MODE 1
#define I2C_SERVO_START_TRANSACTION_SYMBOL_CONFIG_CURRENT_SERVO 2
#define I2C_SERVO_START_TRANSACTION_SYMBOL_CONFIG_MOVE 3
#define I2C_START_TRANSACTION_SYMBOL_SET_MOTOR_SPEED 4
#define I2C_SERVO_START_TRANSACTION_SYMBOL_CONFIG_SAVE_PARAM 5
#define I2C_SERVO_START_TRANSACTION_SYMBOL_DEBUG_ENABLE 6
#define I2C_START_TRANSACTION_SYMBOL_SAVE_MOTOR_SPEED 7
#define I2C_SERVO_START_TRANSACTION_SYMBOL_SET_KINEMATICS_SPEED 8
#define I2C_SERVO_START_TRANSACTION_SYMBOL_REPEAT 9
#define I2C_SERVO_START_TRANSACTION_SYMBOL_SET_REELS_SIZE 10
#define I2C_SERVO_START_TRANSACTION_SYMBOL_CONFIG_CURRENT_PID_REGULATOR 11
#define I2C_SERVO_START_TRANSACTION_SYMBOL_CONFIG_SAVE_PID_KOEF 12
#define I2C_SERVO_START_TRANSACTION_SYMBOL_CONFIG_SEND_PID_KOEF 13

#define I2C_DATA_REEL_SPEED_LEFT 0
#define I2C_DATA_REEL_SPEED_RIGHT 1
#define I2C_DATA_KINEMATICS_MODE_CURRENT 2
#define I2C_DATA_KINEMATICS_IN_PROCESS 3
#define I2C_DATA_REPEAT 4
#define I2C_DATA_TENSION 5

#define I2C_DATA_AUDIO_L 6
#define I2C_DATA_AUDIO_R 7

#define I2C_DATA_SERVO_PLAY_CURRENT_ANGLE 8
#define I2C_DATA_SERVO_REWIND_CURRENT_ANGLE 9
#define I2C_DATA_SERVO_LEFT_CURRENT_ANGLE 10
#define I2C_DATA_SERVO_RIGHT_CURRENT_ANGLE 11

#define I2C_DATA_SERVO_DEBUG_FROM 12
#define I2C_DATA_SERVO_DEBUG_TO 19

#define I2C_DATA_CONFIG_SERVO_MIN 20
#define I2C_DATA_CONFIG_SERVO_MAX 21
#define I2C_DATA_CONFIG_SERVO_PLAY 22
#define I2C_DATA_CONFIG_SERVO_STOP 23
#define I2C_DATA_CONFIG_SERVO_FORWARD 24
#define I2C_DATA_CONFIG_SERVO_REWIND 25
#define I2C_DATA_CONFIG_SERVO_PAUSE 26
#define I2C_DATA_CONFIG_SERVO_SEARCH 27
#define I2C_DATA_CONFIG_MOTOR_SPEED 28

#define I2C_DATA_CONFIG_TENSION_P 6
#define I2C_DATA_CONFIG_TENSION_I 7
#define I2C_DATA_CONFIG_TENSION_D 8

#define I2C_DATA_COUNT 5
#define I2C_DATA_DEBUG_1_COUNT 29
#define I2C_DATA_DEBUG_2_COUNT 9
#define I2C_DATA_ALL_COUNT 29

#define I2C_DEBUG_STR_MAX_LEN 8
char debug_string[I2C_DEBUG_STR_MAX_LEN];

#endif /* M4D_I2C_H_ */